apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mi-pod
  name: mi-pod   #nombre del servicio
spec:
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30100
      targetPort: 80
  selector:
    app: mi-pod
  type: NodePort   #define el tipo de servicio
status:
  loadBalancer: {}
