apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mi-deploy
  name: mi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mi-deploy
    spec:
      containers:
     # - image: andr35/imagen:v0.2.0
      - image: andr35/imagen:v0.3.0
        name: imagen
        ports:
        - containerPort: 80
        resources: {}
status: {}
