version: '3.8'
services:
  web:
    image: andr35/ej2compose-pet:v0.1.0
    ports:
      - "3000:3000"

  db:
    image: andr35/ej2compose-database:v0.1.0
    volumes:
      - pets-data:/var/lib/postgresql/data
 
volumes:
  pets-data: 
