apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mi-app-svc
  name: mi-app-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: mi-pod
  type: ClusterIP
status:
  loadBalancer: {}
