apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mi-pod
  name: mi-pod
spec:
  containers:
  - image: andr35/imagen:v0.1.0
    name: mi-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
