#Version de docker-compose
version: '3'

#Servicios
services:

  #Contenedor I
  book-api:
    build:
      context: ./book-api
    ports:
      - 5001:5000
    volumes:
      - ./book-api/src:/app
    
  #Contenedor II
  front-end:
    build:
      context: ./front-end
    environment:
      - BOOK_API_SERVER=http://book-api:5000
    ports:
      - 5000:5000
    volumes:
      - ./front-end/src:/app
      
